### PR TITLE
Snapshot Tests.

### PR DESCRIPTION
**Pull request by juanky201271**
There are some warnings and a couple of mocking errors. 
@Gunnar-Stunnar maybe you can help me with those problems if you have experience with jest and testing.
Thank you in advance.

### CODE REVIEW

**Comment by juanky201271** [comment]
To run all the test inside of __ tests __ folder is the command:
yarn test

To run the coverage test in components folder, command:
yarn coverage_com

To run the coverage test in app folder, command:
yarn coverage_app

To run the coverage test for App.tsx, command:
yarn coverage_app_tsx

TODO: To run the three in a single command.

**Comment by juanky201271** [comment]
To run all the test inside of __ tests __ folder is the command:
yarn test

To run the coverage test in components folder, command:
yarn coverage_com

To run the coverage test in app folder, command:
yarn coverage_app

To run the coverage test for App.tsx, command:
yarn coverage_app_tsx

TODO: To run the three in a single command.

**Comment by zancas** [comment]
I think this is super important!   Great work @juanky201271 !!

**Comment by juanky201271** [comment]
Persistent error, @Gunnar-Stunnar maybe you can see some light at the end of the tunnel....

image

**Comment by juanky201271** [comment]
The other persistent error is:

image

Thanks in advance.

**Comment by zancas** [comment]
It seems like there should be a matching `}` to go with the `{` right before the png.

Maybe there's a problem with interpreting the png.

As a test can you pull out the png (or mv it aside) and see what happens with `{}`?

**Pull request closed without merging**
