### PR TITLE
settings memo touchable fixed in Android

### PR DESCRIPTION
**Pull request by juanky201271**
This is a known problem, the first recommendation is to use the same component: TouchableOpacity from react-native library instead from: react-native-gesture-handler library.

### CODE REVIEW

**Review by Gunnar-Stunnar — APPROVED** [review]

**Comment by zancas** [comment]
Were you able to test this against your Android 12 device?

**Comment by juanky201271** [comment]
Well, Android 12... I don't think so. The Android Device that I have is Android 11. Otherwise, I reproduce the error in Android 11, and I fixed it... I'm pretty sure that It works in 12 too.

**Comment by juanky201271** [comment]
This PR must to be merge before stunnar create the first version for Android.... It's my opinion.

**Comment by zancas** [comment]
Can we add some kind of test showing that the toggle works?   I don't know which test framework that would be?  `cypress`?

**Comment by juanky201271** [comment]
I think with jest I can do a component test, changing the value of the Toggle... I hope so.

**Comment by juanky201271** [comment]
I solved the conflict.

**Comment by juanky201271** [comment]
Yes, I think so. I'll work on a Unit Component Test using this toggle thingy.

**Comment by juanky201271** [comment]
I added some Unit Test, one of them for the toggle control in settings screen.

**Pull request merged**
